name: abhinav_agency
description: Abhinav Agency location app (starter)
publish_to: "none"

environment:
  sdk: ^3.9.0        # <-- change made

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.0
  geolocator: ^13.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#C7B6FF"
  image: assets/logo/logo.png
  android: true
  ios: false

flutter:
  uses-material-design: true


